apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-mongodb
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup-mongodb
            image: gcr.io/toptal-realworld-app/backup-mongodb:latest
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-uri
                  key: MONGODB_URI              
            - name: GCS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: BUCKET_URI
