apiVersion: v1
kind: Service
metadata:
  name: realworld-backend
  labels:
    app: realworld-backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
  selector:
    app: realworld-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-backend
  labels:
    app: realworld-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realworld-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: realworld-backend
    spec:
      containers:
      - image: gcr.io/toptal-realworld-app/realworld-backend
        imagePullPolicy: Always
        name: realworld-backend
        ports:
        - containerPort: 3001
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: BACKEND_URL
          value: "http://realworld-backend.default.svc.cluster.local:3001"
        - name: MONGODB_STORE_CONNECTION_STRING
          value: "mongodb://test:test@mongodb.default.svc.cluster.local:27017/test"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
