ipersistence:
  storageClassName: prometheus
datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki-stack.loki-stack:3100
      access: proxy
      isDefault: false
service:
  type: LoadBalancer
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    cluster-monitoring-for-kubernetes:
      gnetId: 10000
      revision: 1
      datasource: Prometheus
