apiVersion: v1
kind: Service
metadata:
  name: realworld-frontend
spec:
  selector:
    app: realworld-frontend
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-frontend
  labels:
    app: realworld-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realworld-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: realworld-frontend
    spec:
      containers:
      - image: gcr.io/toptal-realworld-app/realworld-frontend
        imagePullPolicy: Always
        name: realworld-frontend
        ports:
        - containerPort: 3002
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: BACKEND_URL
          value: "http://realworld-backend.default.svc.cluster.local:3001"
        - name: FRONTEND_URL
          value: "http://localhost:3002"
